# Azure Developer CLI (azd) Configuration
# Used for deploying Nova Food Journal to Azure Container Apps

name: ponovaweight
metadata:
  template: custom

# Infrastructure configuration
infra:
  provider: bicep
  path: ./
  module: main

# Service configuration
services:
  api:
    name: ponovaweight-api
    project: ../src/PoNovaWeight.Api
    language: dotnet
    host: containerapp
    docker:
      path: ../src/PoNovaWeight.Api/Dockerfile
      context: ../
      registry:
        endpoint: ponovaweightacr.azurecr.io

# Pipeline configuration for CI/CD
pipeline:
  provider: github

# Environment variables schema
hooks:
  preprovision:
    windows:
      shell: pwsh
      run: |
        Write-Host "Preparing Nova Food Journal deployment..."
        Write-Host "Environment: $env:AZURE_ENV_NAME"
    posix:
      shell: sh
      run: |
        echo "Preparing Nova Food Journal deployment..."
        echo "Environment: $AZURE_ENV_NAME"
  
  postprovision:
    windows:
      shell: pwsh
      run: |
        Write-Host "Deployment complete!"
        Write-Host "App URL: $env:SERVICE_API_ENDPOINT"
    posix:
      shell: sh
      run: |
        echo "Deployment complete!"
        echo "App URL: $SERVICE_API_ENDPOINT"
